const css = `:root{color-scheme:light dark;font-family:system-ui,-apple-system,"Microsoft YaHei",sans-serif;background:#FAF9F5;color:#292724}*{box-sizing:border-box}body{margin:0;min-height:100dvh;display:grid;place-items:center;padding:24px}.card{background:#fff;border:1px solid #dedfd7;border-radius:12px;padding:32px;max-width:440px;width:100%;box-shadow:0 16px 60px #2535200b}.eyebrow{color:#607153;font-size:12px;letter-spacing:.12em}h1{font-size:26px;letter-spacing:-.04em;margin:20px 0 12px}p{font-size:16px;line-height:1.8;color:#687064}button{background:#D97757;border:0;color:white;border-radius:8px;padding:14px 18px;font:inherit;width:100%;cursor:pointer}.status{display:flex;align-items:center;gap:10px;margin:24px 0;color:#D97757;font-size:14px}.dot{width:9px;height:9px;border-radius:50%;background:#D97757}small{color:#80877a;line-height:1.7;display:block} @media(prefers-color-scheme:dark){:root{background:#242321;color:#F0EEE8}.card{background:#222822;border-color:#3a4238}p,small{color:#a7b29f}.status{color:#aac79d}}`
export function pairingPage(): string {
  return `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><link rel="icon" href="data:,"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="referrer" content="no-referrer"><title>连接 DeepSeek Harness</title><style>${css}</style></head><body><main class="card"><span class="eyebrow">DSH · 远程</span><h1>连接你的电脑</h1><p>在电脑上确认这次配对后，你就可以在这里继续使用 DeepSeek Harness。</p><div class="status"><span class="dot"></span><span id="state">正在发送配对请求…</span></div><small>授权后，这台设备与本机拥有相同的操作权限。你可以随时在远程控制面板撤销设备。</small><button id="enter" hidden>进入 DeepSeek Harness</button></main><script>
  (async()=>{const state=document.getElementById('state');const enter=document.getElementById('enter');
  try{const token=new URLSearchParams(location.hash.slice(1)).get('pair');history.replaceState(null,'','/pair');
    if(!token){const health=await fetch('/api/dsh-remote-control/manage',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'status'})});if(health.ok){location.replace('/');return}throw Error('请在电脑上开启远程控制并扫描新的二维码。')}
    const request=await fetch('/rc/pair/request',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({token})});const claim=await request.json();if(!request.ok)throw Error(claim.error||'配对请求失败');
    state.textContent='等待电脑确认，请查看本机远程控制面板';
    while(Date.now()<claim.expiresAt){await new Promise(r=>setTimeout(r,1500));const response=await fetch('/rc/pair/claim',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({id:claim.id,key:claim.key})});const result=await response.json();if(!response.ok)throw Error(result.error||'请求已失效');if(result.state==='rejected')throw Error('电脑已拒绝本次配对。');if(result.state==='approved'){state.textContent='已连接，正在打开远程界面…';location.replace('/');return}}
    throw Error('配对请求已过期，请重新扫码。')
  }catch(error){state.textContent=error.message;enter.hidden=false;enter.textContent='重新检查连接';enter.onclick=()=>location.reload()}})();
  </script></body></html>`
}
export function deniedPage(): string {
  return `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><link rel="icon" href="data:,"><meta name="viewport" content="width=device-width,initial-scale=1"><title>设备尚未授权</title><style>${css}</style></head><body><main class="card"><span class="eyebrow">DSH · 远程</span><h1>需要重新连接</h1><p>这台设备尚未配对，授权已过期，或已被撤销。请在电脑上打开远程控制面板，扫描新的二维码并确认配对。</p><small>关闭远程连接会保留设备授权；临时公网地址变化后，需要重新扫码。</small></main></body></html>`
}

